### ISSUE TITLE
Git repository not found

### ISSUE THREAD

**Issue by Wewannado** [David-Lor/Docker-Python-Git-App#2]
I'm trying to use this Docker container together with your MQTT2MySQL python program but I cannot make it work.

The error I'm encountering is:

```
This is the first time this container gets executed, so we will install the dependencies and main app...
Cleaning output directory...
Cloning app through git...
fatal: repository 'MyApp' does not exist
Previous command failed with exit code 128, container will stop now!
```

I'm trying to run the container with the following:

docker run -d -e GIT_REPOSITORY:https://github.com/David-Lor/MQTT2MySQL.git -e SQL_USER:root -e SQL_PASS:1234 -e SQL_DATABASE:mqtt --name mqtt2mysql davidlor/python-autoclonable-app

Somebody can help me to track and solve the origin of the issue?

**Comment by David-Lor** [comment]
Try using this image: `davidlor/python-autoclonable-app:latest-dev`

(Or build the image in this repository, while is not yet published to DockerHub)

**Comment by Wewannado** [comment]
It works ok with the image you provided.

Thanks.
